# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2026 mp3monster.org

FROM mcr.microsoft.com/playwright:v1.59.1-noble

WORKDIR /opt/agent-shutdown-ui

RUN npm init -y \
    && npm install --omit=dev playwright@1.59.1

COPY tests/test-containers/agent-shutdown-e2e/scripts/drive_shutdown_ui.mjs /opt/agent-shutdown-ui/drive_shutdown_ui.mjs

ENTRYPOINT ["node", "/opt/agent-shutdown-ui/drive_shutdown_ui.mjs"]
